[package]
name = "sdcc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
lazy_static = "1.5.0"
regex = "1.10.5"
strum = "0.26.3"
strum_macros = "0.26.4"
